### ISSUE TITLE
grafana-import-dashboards start error

### ISSUE THREAD

**Issue by zzhao0528** [kayrus/prometheus-kubernetes#5]
Hi,i use this repo to start prometheus-kubernetes, all components start ok but grafana-import-dashboards.
I run `kubectl logs -f ` it show below:
```
syntax error: unexpected "do"
```
My k8s env:
'''
kubernetes: 1.6.3 startup by kubeadm
network: calico bgp
'''
Can u help me?

**Comment by kayrus** [comment]
This [commit](https://github.com/kayrus/prometheus-kubernetes/commit/95dfe1e92456e37c55051ce4319c944886eb0aac) should fix the issue. Can you verify?

**Comment by zzhao0528** [comment]
@kayrus it's OK. LGTM. Thanks very much.
